name: Snyk Scanner
description: Check dependencies with Snyk
inputs:
  packageFile:
    description: The package file to scan for dependencies
    required: false
    default: requirements.txt
  ignore:
    description: Provide list of vulnerabilities to ignore
    required: false
outputs:
  results:
    description: Any found vulnerability results
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'shield'
  color: 'purple'
